browser = chrome

LcfUrl = https://qa.loyalfriendcare.com/en
RegUrl = https://qa.loyalfriendcare.com/en/register
VacUrl = https://qa.loyalfriendcare.com/Pets
MedUrl = https://qa.loyalfriendcare.com/Medicines
DocUrl = https://qa.loyalfriendcare.com/Doctors
DepUrl = https://qa.loyalfriendcare.com/Departments
AboutUrl = https://qa.loyalfriendcare.com/about
DermUrl = https://qa.loyalfriendcare.com/en/Departments/dermatology
LoginUrl = https://qa.loyalfriendcare.com/en/login 
ResetUrl = https://qa.loyalfriendcare.com/en/password/reset


DasUrl = https://qa.loyalfriendcare.com/en/admin
DasrolUrl = https://qa.loyalfriendcare.com/en/Dashboard/Roles
DasuseUrl = https://qa.loyalfriendcare.com/en/Dashboard/Users
DasbedUrl = https://qa.loyalfriendcare.com/en/Dashboard/Posts
DasdepUrl = https://qa.loyalfriendcare.com/en/Dashboard/Categories
DasdocUrl = https://qa.loyalfriendcare.com/en/Dashboard/Clients
DasmedUrl = https://qa.loyalfriendcare.com/en/Dashboard/Instagrams
DaspetUrl = https://qa.loyalfriendcare.com/en/Dashboard/AdSense
DasticUrl = https://qa.loyalfriendcare.com/en/Dashboard/Messages
DasvacUrl = https://qa.loyalfriendcare.com/en/Dashboard/Galleries



T01UserMail = beril.user@loyalfriendcare.com
T01UserPassword = Loyal.123123
T03UserMail = devrim.user@loyalfriendcare.com
T03UserPassword = Loyal.123123
T04UserMail = elifbayrak.user@loyalfriendcare.com
T04UserPassword = Loyal.123123
T05UserMail = farkhod.user@loyalfriendcare.com
T05UserPassword = Loyal.123123
T06UserMail = fatih.user@loyalfriendcare.com
T06UserPassword = Loyal.123123
T07UserMail = gokcen.user@loyalfriendcare.com
T07UserPassword =Loyal.123123
T08UserMail = kadriye.user@loyalfriendcare.com
T08UserPassword = Loyal.123123
T09UserMail = kerim.user@loyalfriendcare.com
T09UserPassword = Loyal.123123
T10UserMail = mehmet.user@loyalfriendcare.com
T10UserPassword = Loyal.123123
T11UserMail = sinem.user@loyalfriendcare.com
T11UserPassword = Loyal.123123

T01AdminMail = beril.admin@loyalfriendcare.com
T01AdminPassword = Loyal.123123
T03AdminMail = devrim.admin@loyalfriendcare.com
T03AdminPassword = Loyal.123123
T04AdminMail = elifbayrak.admin@loyalfriendcare.com
T04AdminPassword = Loyal.123123
T05AdminMail = farkhod.admin@loyalfriendcare.com
T05AdminPassword = Loyal.123123
T06AdminMail = fatih.admin@loyalfriendcare.com
T06AdminPassword = Loyal.123123
T07AdminMail= gokcen.admin@loyalfriendcare.com
T07AdminPassword = Loyal.123123
T08AdminMail = kadriye.admin@loyalfriendcare.com
T08AdminPassword = Loyal.123123
T09AdminMail = kerim.admin@loyalfriendcare.com
T09AdminPassword = Loyal.123123
T10AdminMail = mehmet.admin@loyalfriendcare.com
T10AdminPassword = Loyal.123123
T11AdminMail= sinem.admin@loyalfriendcare.com
T11AdminPassword = Loyal.123123


LcfGecersizMail =mailqmail.com
LcfKayitsizMail =
LcfGecersizPassword =MailNotValidPass101

AranacakKelimePet = "Pet"
AranacakKelimeTest = "Test

