browser = chrome

LcfUrl = https://qa.loyalfriendcare.com/en

LcfGecerliMail =
LcfGecerliPassword =
LcfGecersizMail =
LcfGecersizPassword =

AranacakKelime =

ElifUserEmail=elifbayrak.user@loyalfriendcare.com
ElifUserPassword=Loyal.123123
ElifAdminEmail=elifbayrak.admin@loyalfriendcare.com
ElifAdminPassword=Loyal.123123